Fix NoClassDefFoundError (#645)
* Load plugin in dedicated loader

* Rename to plugin class loader

* Fix NPE

* Add identity hash code to class loader name

* Use toString to replace Json serialization